---
# file: nodejs/tasks/setup.yml
#
# setup.
#

- name: installation | download source tarball
  get_url:
    url="http://nodejs.org/dist/v{{ nodejs_version }}/{{ nodejs_tarball }}"
    dest="{{ nodejs_dir_src }}"
    mode=0440
  become: yes

- name: installation | set tarball ownership
  file:
    path="{{ nodejs_dir_src }}/{{ nodejs_tarball }}"
    state=directory
    owner="{{ ansible_env.USER }}"
    group="{{ ansible_env.USER }}"
  become: yes

- name: installation | ensure unarchive directory exists
  file:
    path="{{ nodejs_dir_src }}/{{ nodejs_prefix }}"
    state=directory
    owner="{{ ansible_env.USER }}"
    group="{{ ansible_env.USER }}"
  become: yes

- name: installation | unpack tarball
  unarchive:
    src="{{ nodejs_dir_src }}/{{ nodejs_tarball }}"
    dest="{{ nodejs_dir_src }}"
    copy=no
    owner="{{ ansible_env.USER }}"
    group="{{ ansible_env.USER }}"
  become: yes

- name: installation | configure
  command: /usr/bin/python ./configure --prefix={{ nodejs_path }}
    chdir="{{ nodejs_dir_src }}/{{ nodejs_prefix }}"

- name: installation | make
  command: /usr/bin/make -j 4
    chdir="{{ nodejs_dir_src }}/{{ nodejs_prefix }}/"

- name: installation | make install
  command: /usr/bin/make install
    chdir="{{ nodejs_dir_src }}/{{ nodejs_prefix }}/"
  become: yes
